# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SamVa\Desktop\TrainingTool.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dialogStartNewSession(object):
    def setupUi(self, dialogStartNewSession):
        dialogStartNewSession.setObjectName(_fromUtf8("dialogStartNewSession"))
        dialogStartNewSession.resize(503, 511)
        self.gridLayout = QtGui.QGridLayout(dialogStartNewSession)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkboxWriteToFile = QtGui.QCheckBox(dialogStartNewSession)
        self.checkboxWriteToFile.setObjectName(_fromUtf8("checkboxWriteToFile"))
        self.gridLayout.addWidget(self.checkboxWriteToFile, 5, 0, 1, 1)
        self.lblQuestionCategories = QtGui.QLabel(dialogStartNewSession)
        self.lblQuestionCategories.setObjectName(_fromUtf8("lblQuestionCategories"))
        self.gridLayout.addWidget(self.lblQuestionCategories, 2, 1, 1, 1)
        self.lblNumberOfQuestions = QtGui.QLabel(dialogStartNewSession)
        self.lblNumberOfQuestions.setObjectName(_fromUtf8("lblNumberOfQuestions"))
        self.gridLayout.addWidget(self.lblNumberOfQuestions, 0, 0, 1, 1)
        self.spinboxNumberOfQuestions = QtGui.QSpinBox(dialogStartNewSession)
        self.spinboxNumberOfQuestions.setObjectName(_fromUtf8("spinboxNumberOfQuestions"))
        self.gridLayout.addWidget(self.spinboxNumberOfQuestions, 0, 1, 1, 1)
        self.lblMediaTypes = QtGui.QLabel(dialogStartNewSession)
        self.lblMediaTypes.setObjectName(_fromUtf8("lblMediaTypes"))
        self.gridLayout.addWidget(self.lblMediaTypes, 2, 0, 1, 1)
        self.listMediaTypes = QtGui.QListWidget(dialogStartNewSession)
        self.listMediaTypes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listMediaTypes.setObjectName(_fromUtf8("listMediaTypes"))
        item = QtGui.QListWidgetItem()
        self.listMediaTypes.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listMediaTypes.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listMediaTypes.addItem(item)
        self.gridLayout.addWidget(self.listMediaTypes, 3, 0, 1, 1)
        self.lblQuestionTypes = QtGui.QLabel(dialogStartNewSession)
        self.lblQuestionTypes.setObjectName(_fromUtf8("lblQuestionTypes"))
        self.gridLayout.addWidget(self.lblQuestionTypes, 2, 2, 1, 1)
        self.listQuestionCategories = QtGui.QListWidget(dialogStartNewSession)
        self.listQuestionCategories.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listQuestionCategories.setObjectName(_fromUtf8("listQuestionCategories"))
        item = QtGui.QListWidgetItem()
        self.listQuestionCategories.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listQuestionCategories.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listQuestionCategories.addItem(item)
        self.gridLayout.addWidget(self.listQuestionCategories, 3, 1, 1, 1)
        self.btnOkCancel = QtGui.QDialogButtonBox(dialogStartNewSession)
        self.btnOkCancel.setEnabled(True)
        self.btnOkCancel.setOrientation(QtCore.Qt.Horizontal)
        self.btnOkCancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.btnOkCancel.setObjectName(_fromUtf8("btnOkCancel"))
        self.gridLayout.addWidget(self.btnOkCancel, 11, 0, 1, 1, QtCore.Qt.AlignRight)
        self.listQuestionTypes = QtGui.QListWidget(dialogStartNewSession)
        self.listQuestionTypes.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listQuestionTypes.setObjectName(_fromUtf8("listQuestionTypes"))
        item = QtGui.QListWidgetItem()
        self.listQuestionTypes.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listQuestionTypes.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listQuestionTypes.addItem(item)
        self.gridLayout.addWidget(self.listQuestionTypes, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 3)
        self.groupBox = QtGui.QGroupBox(dialogStartNewSession)
        self.groupBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cboxEncrypt = QtGui.QCheckBox(self.groupBox)
        self.cboxEncrypt.setObjectName(_fromUtf8("cboxEncrypt"))
        self.gridLayout_2.addWidget(self.cboxEncrypt, 2, 0, 1, 1)
        self.btnBrowseFilename = QtGui.QPushButton(self.groupBox)
        self.btnBrowseFilename.setObjectName(_fromUtf8("btnBrowseFilename"))
        self.gridLayout_2.addWidget(self.btnBrowseFilename, 1, 2, 1, 1)
        self.leditFilename = QtGui.QLineEdit(self.groupBox)
        self.leditFilename.setObjectName(_fromUtf8("leditFilename"))
        self.gridLayout_2.addWidget(self.leditFilename, 1, 1, 1, 1)
        self.lblFilename = QtGui.QLabel(self.groupBox)
        self.lblFilename.setObjectName(_fromUtf8("lblFilename"))
        self.gridLayout_2.addWidget(self.lblFilename, 1, 0, 1, 1)
        self.lblUsername = QtGui.QLabel(self.groupBox)
        self.lblUsername.setObjectName(_fromUtf8("lblUsername"))
        self.gridLayout_2.addWidget(self.lblUsername, 0, 0, 1, 1)
        self.leditUsername = QtGui.QLineEdit(self.groupBox)
        self.leditUsername.setObjectName(_fromUtf8("leditUsername"))
        self.gridLayout_2.addWidget(self.leditUsername, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 6, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 3)

        self.retranslateUi(dialogStartNewSession)
        QtCore.QObject.connect(self.btnOkCancel, QtCore.SIGNAL(_fromUtf8("accepted()")), dialogStartNewSession.accept)
        QtCore.QObject.connect(self.btnOkCancel, QtCore.SIGNAL(_fromUtf8("rejected()")), dialogStartNewSession.reject)
        QtCore.QMetaObject.connectSlotsByName(dialogStartNewSession)

    def retranslateUi(self, dialogStartNewSession):
        dialogStartNewSession.setWindowTitle(_translate("dialogStartNewSession", "Start session", None))
        self.checkboxWriteToFile.setText(_translate("dialogStartNewSession", "Write results to file", None))
        self.lblQuestionCategories.setText(_translate("dialogStartNewSession", "Select question categories", None))
        self.lblNumberOfQuestions.setText(_translate("dialogStartNewSession", "Number of questions", None))
        self.lblMediaTypes.setText(_translate("dialogStartNewSession", "Select media types", None))
        __sortingEnabled = self.listMediaTypes.isSortingEnabled()
        self.listMediaTypes.setSortingEnabled(False)
        item = self.listMediaTypes.item(0)
        item.setText(_translate("dialogStartNewSession", "Type 1", None))
        item = self.listMediaTypes.item(1)
        item.setText(_translate("dialogStartNewSession", "Type 2", None))
        item = self.listMediaTypes.item(2)
        item.setText(_translate("dialogStartNewSession", "Type 3", None))
        self.listMediaTypes.setSortingEnabled(__sortingEnabled)
        self.lblQuestionTypes.setText(_translate("dialogStartNewSession", "Select question types", None))
        __sortingEnabled = self.listQuestionCategories.isSortingEnabled()
        self.listQuestionCategories.setSortingEnabled(False)
        item = self.listQuestionCategories.item(0)
        item.setText(_translate("dialogStartNewSession", "Category 1", None))
        item = self.listQuestionCategories.item(1)
        item.setText(_translate("dialogStartNewSession", "Category 2", None))
        item = self.listQuestionCategories.item(2)
        item.setText(_translate("dialogStartNewSession", "Category 3", None))
        self.listQuestionCategories.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listQuestionTypes.isSortingEnabled()
        self.listQuestionTypes.setSortingEnabled(False)
        item = self.listQuestionTypes.item(0)
        item.setText(_translate("dialogStartNewSession", "QType 1", None))
        item = self.listQuestionTypes.item(1)
        item.setText(_translate("dialogStartNewSession", "QType 2", None))
        item = self.listQuestionTypes.item(2)
        item.setText(_translate("dialogStartNewSession", "QType 3", None))
        self.listQuestionTypes.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("dialogStartNewSession", "File options", None))
        self.cboxEncrypt.setText(_translate("dialogStartNewSession", "Encrypt", None))
        self.btnBrowseFilename.setText(_translate("dialogStartNewSession", "Browse", None))
        self.lblFilename.setText(_translate("dialogStartNewSession", "Filename", None))
        self.lblUsername.setText(_translate("dialogStartNewSession", "Username", None))

